language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t antonio28120/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true antonio28120/react-test npm test

after_success:
  - docker build -t antonio28120/multi-client ./client
  - docker build -t antonio28120/multi-nginx ./nginx
  - docker build -t antonio28120/multi-server ./server
  - docker build -t antonio28120/multi-worker ./worker
  # Login Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to DockerHUB
  - docker push antonio28120/multi-client
  - docker push antonio28120/multi-nginx
  - docker push antonio28120/multi-server
  - docker push antonio28120/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'eu-west-2'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-eu-west-2-037524837329'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
